cem_perguntas = [
"Qual seu completo?",
"Onde e quando você nasceu?",
"Quem são seus pais? (nome, profissão, personalidade, etc)",
"Você tem irmãos? Como eles são/eram?",
"Onde você vive agora e com quem? Descreva o lugar e a pessoa.",
"Qual sua ocupação/profissão?",
"Faça uma descrição completa de si mesmo. Talvez queira considerar fatores como: altura, peso, raça, cabelo, cor do olho, estilo de roupas e tatuagens, cicatrizes ou marcas.",
"A que classe social você pertence?",
"Tem alguma alergia, doença ou outra fraqueza física?",
"É destro ou canhoto?",
"Como é a sua voz/como soa?",
"Quais palavras ou frases você usa frequentemente?",
"O que você tem nos bolsos?",
"Você tem manias estranhas, gírias, hábitos irritantes, ou outra característica peculiar?",
"Como você descreve sua infância no geral?",
"Qual sua memória mais antiga?",
"Qual seu grau de escolaridade?",
"Gosta/Gostava da escola?",
"Onde você aprendeu a maior parte das suas habilidades? Enquanto crescia, teve algum modelo/exemplo a seguir? Se sim, descreva-o.",
"Enquanto crescia, como você se relacionava com os outros membros da sua família?",
"Quando criança, o que você queria ser quando crescesse? Quando criança, quais eram suas atividades favoritas?",
"Quando criança, quais traços de personalidade você demonstrava?",
"Quando criança, você era popular?",
"Quem eram seus amigos e como eles eram? Quando e com quem foi seu primeiro beijo?",
"Você é virgem? Se não, quando e com quem você perdeu a virgindade?",
"Se você é um ser sobrenatural (bruxo, lobisomem, vampiro), conte a história de como você se tornou o que é ou como aprendeu a controlar suas habilidades. Se você é um ser humano normal, descreva qualquer influência do passado que o tenha levado a fazer as coisas que faz hoje.",
"Qual você considera o evento mais importante na sua vida até agora?",
"Quem teve a maior influência sobre você?",
"O que você considera sua maior conquista?",
"Qual seu maior arrependimento?",
"Qual a pior coisa (mais malvada) que você já fez?",
"Você tem registro criminal de qualquer tipo? Em que momento da sua vida você se sentiu mais amedrontado?",
"Qual a coisa mais vergonhosa que já aconteceu com você?",
"Se você pudesse mudar alguma coisa no seu passado, o que seria e por quê?",
"Qual sua melhor memória?",
"Qual sua pior memória?",
"Você é otimista ou pessimista?",
"Qual seu maior medo?",
"Qual sua concepção religiosa?",
"Qual sua concepção política?",
"Qual sua visão sobre sexo?",
"Você é capaz de matar? Sob que circunstâncias matar é aceitável ou inaceitável?",
"Em sua opinião, qual é a pior coisa que um ser humano pode fazer?",
"Você acredita em almas gêmeas e/ou amor verdadeiro?",
"O que você acredita que faz de uma vida bem sucedida?",
"Quão honesto você é sobre seus pensamentos e sentimentos? (Você esconde seu verdadeiro eu dos outros e de que forma?).",
"Você tem algum preconceito?",
"Há algo que você se recuse a fazer sob qualquer circunstância?",
"Por que você se recusa?",
"Por quem ou pelo que você morreria? Ou iria ao extremo?",
"Em geral, como você trata os outros (educadamente, rude, mantendo-os longe etc.)?",
"A maneira que os trata muda dependendo de quão bem os conhece, se sim, como?",
"Quem é a pessoa mais importante na sua vida e por quê?",
"Quem é a pessoa que você mais respeita e por quê? Quem são seus amigos?",
"Você tem melhor amigo/a? Descreva essas pessoas.",
"Você tem um cônjuge ou semelhante? Se sim, descreva essa pessoa. Já se apaixonou alguma vez? Se sim, descreva o que aconteceu.",
"O que você procura em um provável amor?",
"Quão próximo você é da sua família?",
"Já começou sua própria família? Se sim, descreva-os. Se não, você quer? Por que ou por que não?",
"A quem recorreria se estivesse desesperado por ajuda?",
"Você confia em alguém para lhe proteger? Quem e por quê?",
"Se você morrer ou desaparecer, quem sentirá sua falta? Quem é a pessoa que você mais despreza? Por quê?",
"Você tende a discutir com as pessoas ou evita conflitos?",
"Você tende a assumir o papel de líder?",
"Gosta de interagir com grandes grupos de pessoas? Por que ou por que não?",
"Você se importa com o que os outros pensam sobre você?",
"Quais seus hobbies e passatempos favoritos?",
"Qual seu bem mais valioso?",
"Qual sua cor favorita?",
"Qual sua comida favorita?",
"Você gosta de ler? O quê?",
"Qual sua ideia de bom entretenimento (música, filmes, artes, etc.)",
"Você fuma, bebe ou usa drogas? Se sim, por quê? Você quer parar?",
"Como você passa uma noite normal de sábado?",
"O que te faz rir?",
"O que te choca ou ofende?",
"O que você faria se tivesse insônia e precisasse encontrar algo para entreter a si mesmo?",
"Como você lida com stress?",
"Você é espontâneo ou sempre precisa ter um plano? Que coisa boba mais te irrita?",
"Descreva a rotina de um dia normal para você.",
"Como se sente quando essa rotina é quebrada?",
"Qual sua maior força como pessoa?",
"Qual sua maior fraqueza?",
"Se você pudesse mudar alguma coisa sobre si, o que seria?",
"Geralmente é introvertido ou extrovertido?",
"É organizado ou bagunceiro?",
"Diga três coisas na qual você se considera muito bom e três coisas na qual se considera muito ruim.",
"Você gosta de si mesmo?",
"Quais seus motivos para ser um kindred? Seus reais motivos para fazer isso, são diferentes dos que você diz às pessoas?",
"O que você mais deseja realizar na sua vida?",
"Onde você se vê em cinco anos?",
"Se pudesse escolher, como gostaria de morrer?",
"Se você soubesse que vai morrer em 24 horas, diga três coisas que faria no tempo que lhe resta. Pelo que você gostaria de ser lembrado após sua morte?",
"Quais três palavras descrevem melhor sua personalidade?",
"Quais três palavras as outras pessoas provavelmente usariam para descrever você?",
"Que conselho você, player, daria ao seu personagem? (Você pode falar como se ele ou ela estivesse sentado de frente para você, use o tom adequado para que ele ou ela atenda seu conselho)",
]